web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./:/src
        - ./site.conf:/etc/nginx/conf.d/default.conf

jekyll:
    image: jekyll/jekyll:stable
    command: jekyll serve --watch --incremental --source /src  --destination /src/_site
    volumes:
        - ./:/src
